# Gradient Deployments: Fashion-MNIST Example
#
# This is part of our basic deployments example (https://github.com/gradient-ai/Deployments) that shows
#
# 1: Create and train a TensorFlow deep learning model using Workflows
# 2: Deploy the model using Deployments
# 3: Send inference data to the model and receive correct output
#
# This Workflow corresponds to step 3 of the above, and calls infer.py to send inference data to the model
#
# Last updated: Dec 07th 2021

defaults:
  env:
    apiKey: secret:api_key
  resources:
    instance-type: C4

jobs:

  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/gradient-ai/Deployments.git

  SendInferenceData:
    env:
      SERVE_URL: "<add your serving URL from step 2 here>"
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: container@v1
    with:
      args:
        - bash
        - "-c"
        - >-
          cd /inputs/repo && python infer.py
      image: 'nvcr.io/nvidia/tensorflow:21.09-tf2-py3'
