# Gradient Deployments: Fashion-MNIST Example
#
# This is part of our basic deployments example (https://github.com/gradient-ai/Deployments) that shows
#
# 1: Create and train a TensorFlow deep learning model using Workflows
# 2: Deploy the model using Deployments
# 3: Send inference data to the model and receive correct output
#
# This Workflow corresponds to step 2 of the above, and specifies the model that we will deploy
#
# Last updated: Dec 07th 2021

image: tensorflow/serving
port: 8501
models:
  id: ... # Add your model ID from step 1 here. The model ID can be seen under the Models tab in the Gradient GUI.
  path: "/opt/models/trained-model/"
env:
  - name: MODEL_BASE_PATH
    value: /opt/models/trained-model/
  - name: MODEL_NAME
    value: trained-model
resources:
  replicas: 1
  instanceType: C4
